import {StyleSheet, Dimensions} from 'react-native';
const {width, height} = Dimensions.get('screen');
export const styles = StyleSheet.create({
  container: {
    flex: 1,

    paddingTop: 50,
    backgroundColor: '#fff',
  },
  text: {
    color: 'white',
  },
  cover: {width, height: height * 0.25},
  avatar: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    // position: 'relative',
    zIndex: 1,
  },
  avatarimg: {
    width: 200,
    height: 200,
    borderRadius: 150,
    position: 'absolute',
    borderWidth: 5,
    borderColor: 'white',
  },
  logo: {
    width,
    height: height * 0.3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  body: {
    width,
    height: height * 0.2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  input: {
    width: '90%',
    padding: 10,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 10,
    color: 'red',
    marginVertical: 10,
  },
  button: {
    width: '90%',
    height: 50,
    borderColor: 'green',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    // margin: 20,
    marginVertical: 20,
  },
  footer: {
    // width,
    // height: height * 0.1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  signUp: {
    width: 200,
    height: height * 0.1,
    // paddingLeft: 30,
    justifyContent: 'flex-end',
  },
  titleDashboard: {
    fontWeight: '900',
    fontSize: 30,
    color: 'rgb(23,162,184)',
    marginVertical: 30,
  },
  subTitleDashboard: {
    fontSize: 24,
    marginBottom: 20,
  },
  textProfile: {
    fontSize: 16,
  },
  buttonDashboard: {
    width: '40%',
    height: 40,
    backgroundColor: 'rgb(23,162,184)',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  manageDashboard: {
    // flex: 1,
  },
  buttonManageDashboard: {
    width: '100%',
    height: 40,
    backgroundColor: 'rgb(23,162,184)',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
  },
  title: {
    fontWeight: '700',
    fontSize: 24,
    marginVertical: 20,
  },
  titleTable: {
    flexDirection: 'row',
    backgroundColor: '#eee',
  },
  subTitleTable: {
    width: '35%',
    textAlign: 'center',
    height: 40,
    lineHeight: 40,
    marginRight: 20,
    fontWeight: '700',
    fontSize: 16,
    borderRightWidth: 2,
    borderRightColor: '#fff',
    backgroundColor: '#eee',
  },
  listItemExp: {
    flexDirection: 'row',
    width: '90%',
  },
  itemEXp: {
    width: '40%',
    textAlign: 'center',
    height: 40,
    lineHeight: 40,
    marginRight: 10,
  },
  buttonDelete: {
    backgroundColor: 'red',
    width: 75,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonLogout: {
    backgroundColor: 'red',
    width: 90,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 30,
  },
  inputSelectBox: {
    marginTop: 20,
    width: '90%',
    fontSize: 14,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'gray',
    borderRadius: 8,
    color: 'black',
    paddingRight: 30, //
  },
  buttonAddSocial: {
    width: '70%',
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    backgroundColor: '#DDD',
    padding: 10,
  },
  textSmall: {
    color: 'gray',
  },
  inputEdit: {
    width: '90%',
    padding: 10,
    borderWidth: 1,
    borderColor: 'gray',
    marginVertical: 10,
  },
  buttonSubmit: {
    width: 100,
    height: 40,
    backgroundColor: 'rgb(23,162,184)',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  buttonGoBack: {
    width: 100,
    height: 40,
    backgroundColor: '#DDD',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 20,
  },
  title: {fontSize: 30, fontWeight: '800'},
  name: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 120,
    marginBottom: 20,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: '600',
  },
});
