export const SIGN_UP_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const CHECK_PROFILE_REQUEST = 'CHECK_PROFILE_REQUEST';
export const CHECK_PROFILE_SUCCESS = 'CHECK_PROFILE_SUCCESS';
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
